name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: escemi-tech/actions-node@v1.7.0
        with:
          checks: true

  publish:
    needs: continuous-integration
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: escemi-tech/actions-node@v1.7.0
        with:
          checkout: '{ "token": "${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}" }'

      - name: 📖 Build docs
        run: |
          yarn build:doc

          mkdir -p /tmp
          cp -R build/docs /tmp/publish
          cp -R docs /tmp/publish/

      - name: 🔖 Prepare release
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

          npx standard-version

          echo `git add -A && git commit -m "chore: prepare release"`
          git push --follow-tags origin ${{ github.event.repository.default_branch }}

      - name: 🌐 Publish Github pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/publish
          enable_jekyll: true
          user_name: ${{ github.actor }}
          user_email: ${{ github.actor }}@users.noreply.github.com

      - name: 📦 Publish NPM packages
        env:
          NPM_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

          npm publish --access public
