name: 🚀 Release

on:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/__shared-ci.yml
    secrets: inherit

  release:
    name: 🚀 Release
    needs: ci
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}

      - uses: hoverkraft-tech/ci-github-nodejs/actions/setup-node@0.6.0

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: /

      - name: 🔖 Configure publish
        env:
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

      - name: 📦 Publish NPM packages
        env:
          GH_TOKEN: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
        run: |
          npx standard-version

          echo `git add -A && git commit -m "chore: prepare release"`
          git push --follow-tags origin ${{ github.event.repository.default_branch }}

          npm publish --access public

      - name: 🌐 Publish to gh-pages
        run: |
          mkdir -p /tmp
          cp -R build/docs /tmp/publish
          cp -R docs /tmp/publish/

      - name: 🌐 Publish Github pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/publish
          enable_jekyll: true
          user_name: ${{ github.actor }}
          user_email: ${{ github.actor }}@users.noreply.github.com
